#define SHIFT(key)  (MODIFIERKEY_SHIFT + (key))

/* qwerty */


int layer0[44] = {
  KEY_Q, KEY_W, KEY_E, KEY_R, KEY_T, KEY_0, KEY_Y, KEY_U, KEY_I, KEY_O, KEY_P,
  KEY_A, KEY_S, KEY_D, KEY_F, KEY_G, KEY_0, KEY_H, KEY_J, KEY_K, KEY_L, KEY_SEMICOLON,
  KEY_Z, KEY_X, KEY_C, KEY_V, KEY_B, MODIFIERKEY_GUI, KEY_N, KEY_M, KEY_COMMA, KEY_PERIOD, KEY_SLASH,
  KEY_ESC, KEY_TAB, MODIFIERKEY_ALT, MODIFIERKEY_SHIFT, KEY_BACKSPACE, MODIFIERKEY_CTRL, KEY_SPACE, 201, KEY_MINUS, KEY_QUOTE, KEY_ENTER };

int layer1[44] = {
  SHIFT(KEY_1), SHIFT(KEY_2), KEY_UP, SHIFT(KEY_LEFT_BRACE), SHIFT(KEY_RIGHT_BRACE), KEY_0, KEY_PAGE_UP, KEYPAD_7, KEYPAD_8, KEYPAD_9, SHIFT(KEY_8),
  SHIFT(KEY_3), KEY_LEFT, KEY_DOWN, KEY_RIGHT, SHIFT(KEY_4),                         KEY_0, KEY_PAGE_DOWN, KEYPAD_4, KEYPAD_5, KEYPAD_6, SHIFT(KEY_EQUAL),
  KEY_LEFT_BRACE, KEY_RIGHT_BRACE, SHIFT(KEY_9), SHIFT(KEY_0), SHIFT(KEY_7), MODIFIERKEY_GUI, KEY_TILDE, KEYPAD_1, KEYPAD_2, KEYPAD_3, KEY_BACKSLASH,
  112, KEY_NUM_LOCK, MODIFIERKEY_ALT, MODIFIERKEY_SHIFT, KEY_BACKSPACE, MODIFIERKEY_CTRL, KEY_SPACE, 201, KEY_PERIOD, KEYPAD_0, KEY_EQUAL };

int layer2[44] = {
    KEY_HOME, KEY_UP, KEY_END, KEY_INSERT, KEY_PAGE_UP, KEY_0, KEY_UP, KEY_F7, KEY_F8, KEY_F9, KEY_F10,
    KEY_LEFT, KEY_DOWN, KEY_RIGHT, KEY_DELETE, KEY_PAGE_DOWN, KEY_0, KEY_DOWN, KEY_F4, KEY_F5, KEY_F6, KEY_F11,
    0, 0, 0, 0, 110, MODIFIERKEY_GUI, 0, KEY_F1, KEY_F2, KEY_F3, KEY_F12,
    0, 0, MODIFIERKEY_ALT, MODIFIERKEY_SHIFT, KEY_BACKSPACE, MODIFIERKEY_CTRL, KEY_SPACE, 201, 0, 0, 0 };

int *layers[] = {layer0, layer1, layer2};

#include "layout_common.h"
