#!/bin/bash

set -e

executable=$1

success=0

tests="add colon constvar no-conditional yes-conditional nested-if if-else"
tests="$tests begin-again do-loop inc"

for test in $tests; do
    echo "Testing $test..."
    result=$(cat tests/${test}.fs | $executable || true)
    if [ "$result" != "$(cat tests/$test)" ]; then
        echo "   FAIL $test: ${!test}"
        echo $result
        success=1
    fi
done

if [ $success -eq 0 ]; then
    echo "Tests pass!"
else
    exit $success
fi
